sudo: required
services:
  - docker
language: go
go:
 - "1.10.x"
env:
  - TEAMCITY_HOST=http://localhost:8112

script:
 # run unit tests first before acceptance tests
 # run acceptance tests
 - integration_tests/start_teamcity.sh  # start and wait for TeamCity
 - go test -v -timeout 30s ./...
