version: '2'
services:
  teamcity10:
    image: jetbrains/teamcity-server:2017.2.1
    ports:
      - 8112:8111
    volumes:
      - /docker/data/teamcity_server/datadir:/data/teamcity_server/datadir
      - /docker/data/teamcity_server/logs:/opt/teamcity/logs
  agent10:
    image: jetbrains/teamcity-agent:2017.2.1
    depends_on:
      - teamcity10
    links:
      - teamcity10
    environment:
      SERVER_URL: http://teamcity10:8111/
    volumes:
      - /docker/data/teamcity_agent/:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock