# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.1
    environment:
      GO111MODULE: "on"
      TEAMCITY_ADDR: "http://localhost:8112"
      TEAMCITY_VERSION: "2018.1.3"
      CONTAINER_NAME: "teamcity_server"
      INTEGRATION_TEST_DIR: "integration_tests"
      TEAMCITY_DATA_DIR: "integration_tests/data_dir"
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - setup_remote_docker
      - run: |
            docker create -v /data/teamcity_server/datadir --name data alpine:3.4 /bin/true
            test -d ${TEAMCITY_DATA_DIR} || tar xfz ${INTEGRATION_TEST_DIR}/teamcity_data.tar.gz -C ${INTEGRATION_TEST_DIR}
            docker cp ${INTEGRATION_TEST_DIR}/data_dir data:/data/teamcity_server/datadir
            docker run --rm -d -p 8112:8111 \
            --volumes-from data \
            jetbrains/teamcity-server:${TEAMCITY_VERSION}
            echo -n "Teamcity server is booting (this may take a while)..."
            until $$(curl -o /dev/null -sfI ${TEAMCITY_HOST}/login.html);do echo -n ".";sleep 5;done
            go test -v -failfast -timeout 180s ./...